# ============================================================================
# SCRIPT: 03_nfhs4_plot_shp_creating_dhs_data_20250807_v3.R
# ============================================================================
#
# PURPOSE
# -------
# Merges NFHS-4 TFR summary estimates with DHS spatial shapefiles to create spatial objects for mapping.
#
# INPUT DATA
# ----------
# - output/tfr_summary_m7_age_nfhs4_20250807_v1.rds (Generated by script 01)
# - data/nfhs4_dhs_official_sf.rds (External restricted DHS shapefile)
#
# OUTPUTS
# -------
# - data/nfhs4_tfr_sf.rds
# - output/nfhs4_tfr_sf.rds
#
# DEPENDENCIES
# ------------
# - script/01_nfhs4_age_fertility_rates_whole_20250807_v2.R
# ============================================================================

# ============================================================================ #
# 1. Load required libraries
# ============================================================================ #
library(tidyverse)   # Data manipulation & visualization
library(here)        # File path management
library(sf)          # Spatial data handling

# ============================================================================ #
# 2. Load TFR summary and shapefile data
# ============================================================================ #
# Load NFHS-4 TFR Summary Data
nfhs4 <- read_rds(here("output", "tfr_summary_m7_age_nfhs4_20250807_v1.rds"))

# Extract only the TFR summary from the loaded list
nfhs4 <- nfhs4$tfr_district

# Load NFHS-4 Shapefile Data
nfhs4_shp <- read_rds(here("data", "nfhs4_dhs_official_sf.rds"))

# ============================================================================ #
# 3. Clean and standardize state/district names
# ============================================================================ #
nfhs4_shp <- nfhs4_shp |> 
  janitor::clean_names() |> 
  mutate(
    state    = othregna,
    district = regname,
    state    = case_when(
      state == "Himanchal Pradesh" ~ "Himachal Pradesh", 
      state == "Jammu & Kashmir"   ~ "Jammu and Kashmir",
      TRUE                         ~ state
    )
  )

# Check for state name mismatches
setdiff(nfhs4$state, nfhs4_shp$state)

# ============================================================================ #
# 4. Create unique identifiers for merging
# ============================================================================ #
# Create Unique IDs for NFHS-4 Data
nfhs4 <- nfhs4 |> 
  mutate(
    unique_id = paste0(str_to_lower(state), " ", str_to_lower(district)),
    unique_id = str_remove_all(unique_id, "&"),
    unique_id = str_squish(unique_id),
    unique_id = str_replace_all(unique_id, " ", "_")
  )

# Create Unique IDs for Shapefile Data
nfhs4_shp <- nfhs4_shp |> 
  mutate(
    unique_id = paste0(str_to_lower(state), " ", str_to_lower(district)),
    unique_id = str_remove_all(unique_id, "&"),
    unique_id = str_squish(unique_id),
    unique_id = str_replace_all(unique_id, " ", "_")
  )

# Check matching IDs between data and shapefile
unique(nfhs4$unique_id) %in% unique(nfhs4_shp$unique_id)
setdiff(unique(nfhs4$unique_id), unique(nfhs4_shp$unique_id))
setdiff(unique(nfhs4_shp$unique_id), unique(nfhs4$unique_id))

# ============================================================================ #
# 5. Merge, label, and save spatial data
# ============================================================================ #
# Merge NFHS-4 Data with Shapefile
nfhs4_sf <- nfhs4_shp |> 
  select(state, district, unique_id, geometry) |> 
  left_join(nfhs4, by = join_by(unique_id))

# Add Data Source Label
nfhs4_sf <- nfhs4_sf %>% 
  mutate(data = "NFHS 4")

# Save Merged Spatial Data
write_rds(nfhs4_sf, here("data", "nfhs4_tfr_sf.rds"))

# ============================================================================ #
# 6. Basic validation map
# ============================================================================ #
nfhs4_sf %>% 
  ggplot() +
  geom_sf(aes(fill = tfr_mean))
