# ============================================================================
# SCRIPT: 04_nfhs5_plot_shp_creating_dhs_data_20250807_v3.R
# ============================================================================
#
# PURPOSE
# -------
# Merges NFHS-5 TFR summary estimates with DHS spatial shapefiles to create spatial objects for mapping.
#
# INPUT DATA
# ----------
# - output/tfr_summary_m7_age_nfhs5_20250807_v1.rds (Generated by script 02)
# - data/nfhs5_dhs_official_sf.rds (External restricted DHS shapefile)
#
# OUTPUTS
# -------
# - data/nfhs5_tfr_sf_20250807.rds
# - output/nfhs5_tfr_sf_20250807.rds
#
# DEPENDENCIES
# ------------
# - script/02_nfhs5_age_fertility_rates_whole_20250807_v2.R
# ============================================================================

# ============================================================================
# 1. Load Required Libraries
# ============================================================================
library(tidyverse)
library(here)
library(sf)

# ============================================================================
# 2. Load NFHS-5 TFR Summary Data
# ============================================================================
nfhs5 <- read_rds(here("output", "tfr_summary_m7_age_nfhs5_20250807_v1.rds"))

# Extract only the TFR summary from the loaded list
nfhs5 <- nfhs5$tfr_district

# ============================================================================
# 3. Standardize State Names & Create Unique IDs
# ============================================================================
nfhs5 <- nfhs5 |>
  mutate(
    state = case_when(
      state == "Jammu  Kashmir" ~ "Jammu & Kashmir",
      state == "Dadra  Nagar Haveli And Daman  Diu" ~ "Dadra & Nagar Haveli & Daman & Diu",
      state == "Andaman  Nicobar Islands" ~ "Andaman & Nicobar Islands",
      TRUE ~ state
    )
  ) |> 
  mutate(
    unique_id = paste0(str_to_lower(state), " ", str_to_lower(district)),
    unique_id = str_remove_all(unique_id, "&"),
    unique_id = str_squish(unique_id),
    unique_id = str_replace_all(unique_id, " ", "_")
  )

# ============================================================================
# 4. Load NFHS-5 Shapefile Data
# ============================================================================
nfhs5_shp <- read_rds(here("data", "nfhs5_dhs_official_sf.rds"))

# Clean column names, rename, and create unique IDs
nfhs5_shp <- nfhs5_shp |> 
  janitor::clean_names() |> 
  mutate(
    state    = othregna,
    district = regname
  ) |> 
  mutate(
    unique_id = paste0(str_to_lower(state), " ", str_to_lower(district)),
    unique_id = str_remove_all(unique_id, "&"),
    unique_id = str_squish(unique_id),
    unique_id = str_replace_all(unique_id, " ", "_")
  )

# ============================================================================
# 5. Check Matching IDs Between Data and Shapefile
# ============================================================================
unique(nfhs5$unique_id) %in% unique(nfhs5_shp$unique_id)

setdiff(unique(nfhs5$unique_id), unique(nfhs5_shp$unique_id))
setdiff(unique(nfhs5_shp$unique_id), unique(nfhs5$unique_id))

# ============================================================================
# 6. Correct Specific Unique ID Mismatches
# ============================================================================
nfhs5 <- nfhs5 |>
  mutate(
    unique_id = case_when(
      unique_id == "uttar_pradesh_mahrajganj" ~ "uttar_pradesh_maharajganj",
      unique_id == "uttar_pradesh_sant_ravidas_nagar_(bhadohi)" ~ "uttar_pradesh_sant_ravidas_nagar",
      unique_id == "bihar_buxar" ~ "bihar_buxer",
      unique_id == "chhattisgarh_janjgir_-_champa" ~ "chhattisgarh_janjgir-champa",
      unique_id == "dadra_nagar_haveli_and_daman_diu_diu" ~ "dadra_nagar_haveli_daman_diu_diu",
      unique_id == "dadra_nagar_haveli_and_daman_diu_daman" ~ "dadra_nagar_haveli_daman_diu_daman",
      unique_id == "dadra_nagar_haveli_and_daman_diu_dadra_nagar_haveli" ~ "dadra_nagar_haveli_daman_diu_dadra_nagar_haveli",
      unique_id == "ladakh_leh(ladakh)" ~ "ladakh_leh",
      TRUE ~ unique_id
    )
  )

# Check again after corrections
unique(nfhs5$unique_id) %in% unique(nfhs5_shp$unique_id)
setdiff(unique(nfhs5_shp$unique_id), unique(nfhs5$unique_id))

# ============================================================================
# 7. Merge NFHS-5 Data with Shapefile
# ============================================================================
nfhs5_sf <- nfhs5_shp |> 
  select(state, district, unique_id, geometry) |> 
  left_join(nfhs5, by = join_by(unique_id))

# ============================================================================
# 8. Save Merged Spatial Data
# ============================================================================
write_rds(nfhs5_sf, here("data", "nfhs5_tfr_sf_20250807.rds"))

# Add Data Source Label
nfhs5_sf <- nfhs5_sf %>% 
  mutate(data = "NFHS 5")

write_rds(nfhs5_sf, here("output", "nfhs5_tfr_sf_20250807.rds"))

# ============================================================================
# 9. Plot NFHS-5 TFR Map
# ============================================================================
nfhs5_sf %>% 
  ggplot() +
  geom_sf(aes(fill = tfr_mean))
