# ============================================================================
# SCRIPT: 05_plot_all_tfr_20250807_v3.R
# ============================================================================
#
# PURPOSE
# -------
# Generates national maps of district-level TFR for both NFHS-4 and NFHS-5, providing a geographic overview of fertility decline.
#
# INPUT DATA
# ----------
# - output/tfr_summary_m7_age_nfhs4_20250807_v1.rds (Generated by 01)
# - output/tfr_summary_m7_age_nfhs5_20250807_v1.rds (Generated by 02)
# - data/census11_irudaya_sf_20250703_v2.rds (External shapefile)
# - data/india_shp_census11.rds (External shapefile)
#
# OUTPUTS
# -------
# - output/map/tfr_india_20250807.png (Figure 1)
#
# DEPENDENCIES
# ------------
# - script/01_..., script/02_...
# ============================================================================

# ============================================================================
# 1. Load Required Libraries
# ============================================================================
library(tidyverse)
library(here)
library(sf)
library(ggspatial)
library(janitor)
library(viridisLite)

# ============================================================================
# 2. Load & Clean NFHS-5 TFR Data
# ============================================================================

# Read NFHS-5 summary data
nfhs5 <- read_rds(here("output", "tfr_summary_m7_age_nfhs5_20250807_v1.rds"))$tfr_district

# Standardize state names and create a clean unique_id
nfhs5 <- nfhs5 %>%
  mutate(
    state = case_when(
      state == "Jammu  Kashmir" ~ "Jammu & Kashmir",
      state == "Dadra  Nagar Haveli And Daman  Diu" ~ "Dadra & Nagar Haveli & Daman & Diu",
      state == "Andaman  Nicobar Islands" ~ "Andaman & Nicobar Islands",
      TRUE ~ state
    ),
    unique_id = paste0(str_to_lower(state), " ", str_to_lower(district)),
    unique_id = str_remove_all(unique_id, "&"),
    unique_id = str_squish(unique_id),
    unique_id = str_replace_all(unique_id, " ", "_")
  )

# Read NFHS-5 shapefile
nfhs5_shp <- read_rds(here("data", "nfhs5_dhs_official_sf.rds")) %>%
  janitor::clean_names() %>%
  mutate(
    state = othregna,
    district = regname,
    unique_id = paste0(str_to_lower(state), " ", str_to_lower(district)),
    unique_id = str_remove_all(unique_id, "&"),
    unique_id = str_squish(unique_id),
    unique_id = str_replace_all(unique_id, " ", "_")
  )

# Harmonize mismatched district IDs
nfhs5 <- nfhs5 %>%
  mutate(unique_id = case_when(
    unique_id == "uttar_pradesh_mahrajganj" ~ "uttar_pradesh_maharajganj",
    unique_id == "uttar_pradesh_sant_ravidas_nagar_(bhadohi)" ~ "uttar_pradesh_sant_ravidas_nagar",
    unique_id == "bihar_buxar" ~ "bihar_buxer",
    unique_id == "chhattisgarh_janjgir_-_champa" ~ "chhattisgarh_janjgir-champa",
    unique_id == "dadra_nagar_haveli_and_daman_diu_diu" ~ "dadra_nagar_haveli_daman_diu_diu",
    unique_id == "dadra_nagar_haveli_and_daman_diu_daman" ~ "dadra_nagar_haveli_daman_diu_daman",
    unique_id == "dadra_nagar_haveli_and_daman_diu_dadra_nagar_haveli" ~ "dadra_nagar_haveli_daman_diu_dadra_nagar_haveli",
    unique_id == "ladakh_leh(ladakh)" ~ "ladakh_leh",
    TRUE ~ unique_id
  ))

# Join NFHS-5 shapefile with TFR data
nfhs5_sf <- nfhs5_shp %>%
  select(state, district, unique_id, geometry) %>%
  left_join(nfhs5, by = "unique_id") %>%
  mutate(data = "NFHS 5")

# Save cleaned NFHS-5 spatial data
write_rds(nfhs5_sf, here("data", "nfhs5_tfr_sf_20250807.rds"))
write_rds(nfhs5_sf, here("output", "nfhs5_tfr_sf_20250807.rds"))

# ============================================================================
# 3. Load NFHS-4 & Census Data
# ============================================================================
nfhs4 <- read_rds(here("data", "nfhs4_tfr_sf.rds"))

census <- read_rds(here("data", "census11_irudaya_sf_20250703_v2.rds")) %>%
  rename(tfr_mean = tfr)

# ============================================================================
# 4. Combine All Data Sources
# ============================================================================

df <- nfhs4 %>%
  bind_rows(nfhs5_sf) %>%
  bind_rows(census) %>%
  mutate(
    # Original 9-category map
    tfr_cat = case_when(
      tfr_mean <= 1.50 ~ "≤1.50",
      tfr_mean <= 1.80 ~ ">1.50–1.80",
      tfr_mean <= 2.10 ~ ">1.80–2.10",
      tfr_mean <= 2.40 ~ ">2.10–2.40",
      tfr_mean <= 2.70 ~ ">2.40–2.70",
      tfr_mean <= 3.00 ~ ">2.70–3.00",
      tfr_mean <= 3.50 ~ ">3.00–3.50",
      tfr_mean <= 4.00 ~ ">3.50–4.00",
      tfr_mean > 4.00  ~ ">4.00",
      TRUE ~ NA_character_
    ),
    
    # 5-category map
    tfr_cat5 = case_when(
      tfr_mean <= 1.50 ~ "≤1.5",
      tfr_mean <= 2.10 ~ ">1.5–2.1",
      tfr_mean <= 3.00 ~ ">2.1–3.0",
      tfr_mean <= 4.00 ~ ">3.0–4.0",
      tfr_mean > 4.00  ~ ">4.0",
      TRUE ~ NA_character_
    ),
    
    # 3-category map
    tfr_cat3 = case_when(
      tfr_mean <= 2.10 ~ "Below replacement (≤2.1)",
      tfr_mean <= 3.00 ~ "Moderate (>2.1–3.0)",
      tfr_mean > 3.00  ~ "High (>3.0)",
      TRUE ~ NA_character_
    )
  )

# ============================================================================
# 5. Identify Disputed / Missing Areas
# ============================================================================

ind_sf <- read_rds(here("data", "india_shp_census11.rds"))

nfhs5_valid <- st_make_valid(
  st_transform(nfhs5_sf, st_crs(ind_sf))
)

ind_sf_valid <- st_make_valid(ind_sf)

non_overlap <- st_difference(
  ind_sf_valid,
  st_union(nfhs5_valid)
) %>%
  filter(
    str_detect(dstrct_nq, "jammu") |
      str_detect(dstrct_nq, "lad")
  )

# ============================================================================
# 6. Format Categories & Factors
# ============================================================================

df <- df %>%
  mutate(
    tfr_cat = factor(
      ifelse(is.na(tfr_cat), "Data Not Available", tfr_cat),
      levels = c(
        "≤1.50", ">1.50–1.80", ">1.80–2.10", ">2.10–2.40", ">2.40–2.70",
        ">2.70–3.00", ">3.00–3.50", ">3.50–4.00", ">4.00", "Data Not Available"
      )
    ),
    tfr_cat5 = factor(
      ifelse(is.na(tfr_cat5), "Data Not Available", tfr_cat5),
      levels = c(
        "≤1.5", ">1.5–2.1", ">2.1–3.0", ">3.0–4.0", ">4.0", "Data Not Available"
      )
    ),
    tfr_cat3 = factor(
      ifelse(is.na(tfr_cat3), "Data Not Available", tfr_cat3),
      levels = c(
        "Below replacement (≤2.1)", "Moderate (>2.1–3.0)", "High (>3.0)", "Data Not Available"
      )
    )
  )

df |> 
  select(data, 1:3, tfr_mean, tfr_median, tfr_lower, tfr_upper, geometry) |> 
  rename("state" = state.x,
         "district" = district.x) |> 
  write_rds(here("output", "census_nfhs45_tfr_combined.rds"))

# ============================================================================
# 7. Generate TFR Maps
# ============================================================================

# Remove Census and relabel for the map
df <- df %>%
  filter(data != "Census 2011") %>%
  mutate(
    data = case_when(
      data == "NFHS 4" ~ "2015–16",
      data == "NFHS 5" ~ "2019–21",
      TRUE ~ NA_character_
    )
  )

# Define final palette
tfr_colors <- c(viridisLite::viridis(9, option = "F", direction = -1), "grey")

p <- ggplot(df) +
  geom_sf(aes(fill = tfr_cat)) +
  geom_sf(data = non_overlap, fill = "grey") +
  scale_fill_manual(values = tfr_colors) +
  labs(fill = "Total Fertility Rate") +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 12, face = "bold"),
    plot.background = element_rect(fill = "white"),
    panel.border = element_blank(),
    plot.title = element_text(
      size = 14,
      face = "bold",
      color = "darkblue",
      hjust = 0.5
    )
  ) +
  annotation_scale(
    location = "bl",
    width_hint = 0.2
  ) +
  annotation_north_arrow(
    location = "tr",
    which_north = "true",
    pad_x = unit(0.2, "in"),
    pad_y = unit(2, "in"),
    style = north_arrow_fancy_orienteering
  ) +
  facet_wrap(~data)

p

# Save map
ggsave(here("output", "map", "tfr_india_20250807.png"), plot = p, width = 7.89, height = 4.04)

# ============================================================================
# 8. Generate Summary Table
# ============================================================================

df |> 
  mutate(tfr_cat1 =  case_when(
    tfr_mean <= 1.5 ~ "<= 1.5",
    between(tfr_mean, 1.50, 2.10) ~ "> 1.50 and <= 2.10",
    between(tfr_mean, 2.10, 3.00) ~ "> 2.10 and <= 3.00",
    between(tfr_mean, 3.00, 4.00) ~ "> 3.00 and <= 4.00",
    tfr_mean > 4 ~ "> 4.00",
    TRUE ~ NA_character_
  ),
  tfr_cat = factor(tfr_cat, levels = c(
    "<= 1.5", "> 1.50 and <= 2.10",
    "> 2.10 and <= 3.00","> 3.00 and <= 4.00", "> 4.00"
  ))) |> 
  st_drop_geometry() |> 
  select(tfr_cat1, data) |> 
  gtsummary::tbl_summary(by = data)

